version: 2
jobs:
  build:
    docker:
        - image: circleci/python:latest
    steps:
        - checkout
        - run: 
            name: Install unittest
            command: pip install unittest
        - run:
            name: Run tests
            command: python test.py 